# Generated by Django 5.1 on 2025-03-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='active',
        ),
    ]
