# Generated by Django 5.1.6 on 2025-03-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mentor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
