# Generated by Django 5.1.6 on 2025-03-01 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_performancereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employee.employee'),
        ),
    ]
