# Generated by Django 5.1.6 on 2025-03-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_session_name_trainingsession_course_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingSession',
        ),
    ]
