# Generated by Django 5.1.6 on 2025-03-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_delete_trainingsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mentor',
        ),
    ]
