# Generated by Django 5.1 on 2025-03-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_attendance_overtime_hours_alter_attendance_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
