# Generated by Django 5.1 on 2025-03-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryhistory',
            name='new_salary',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='previous_salary',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
