# Generated by Django 5.1.6 on 2025-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_employee_salary_currency_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary_currency',
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
